PREFIX ma_prop: <https://makg.org/property/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

DELETE { ?s ma_prop:hasParent ?o . }
INSERT { ?s skos:broader ?o . }
WHERE { ?s ma_prop:hasParent ?o . }
